# Generated by Django 5.1.3 on 2024-11-15 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=255, null=True)),
                ('correo', models.EmailField(max_length=255, null=True)),
                ('direccion', models.CharField(max_length=255, null=True)),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('telefono', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=255, null=True)),
                ('direccion', models.CharField(max_length=255, null=True)),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('telefono', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes_productos/')),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('precio', models.FloatField(null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsol.categoria')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsol.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsol.producto')),
            ],
        ),
        migrations.CreateModel(
            name='favorito',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsol.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField(null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsol.empleado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.FloatField(null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsol.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsol.venta')),
            ],
        ),
    ]
