# Generated by Django 5.0 on 2024-11-29 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsol', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ubicacion',
            old_name='departamento',
            new_name='latitud_y_longitud',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='distrito',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='provincia',
        ),
    ]
