# Generated by Django 5.0 on 2024-11-17 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsol', '0002_carrito_venta_carrito_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='empleado',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
