# Generated by Django 5.0 on 2024-11-17 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsol', '0003_remove_venta_empleado_delete_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_entrada',
            fields=[
                ('id_reegitro', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsol.producto')),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsol.proveedor')),
            ],
        ),
    ]
