# Generated by Django 5.0 on 2024-11-18 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsol', '0004_registro_entrada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
