# Generated by Django 5.0 on 2024-11-18 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsol', '0005_delete_inventario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_entrada',
            old_name='provedor',
            new_name='proveedor',
        ),
    ]
