# Generated by Django 5.0 on 2024-11-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsol', '0006_rename_provedor_registro_entrada_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
