# Generated by Django 5.0 on 2024-11-18 17:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsol', '0007_carrito_cantidad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registro_entrada',
            new_name='RegistroEntrada',
        ),
        migrations.RenameField(
            model_name='favorito',
            old_name='User',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='registroentrada',
            old_name='id_reegitro',
            new_name='id_registro',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='producto',
        ),
        migrations.AddField(
            model_name='carrito',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='carrito',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='factura',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsol.carrito'),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsol.carrito'),
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id_item', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='elsol.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsol.producto')),
            ],
        ),
    ]
